GET {{bromcom_odata_url}}/Students?$filter=TutorGroup eq '9W'
Authorization: Basic {{username}} {{password}}

###

GET {{bromcom_odata_url}}/Collections?$filter=CollectionDescription eq '9W'
Authorization: Basic {{username}} {{password}}

###
GET {{bromcom_odata_url}}
Authorization: Basic {{username}} {{password}}


###
GET {{bromcom_odata_url}}/Staff?$filter=StaffId eq 6963
Authorization: Basic {{username}} {{password}}

###
GET {{bromcom_odata_url}}/CollectionExecutives?$filter=CollectionID eq 89 and CollectionRoleTypeDescription eq 'Main Tutor'
Authorization: Basic {{username}} {{password}}

###
GET {{bromcom_odata_url}}/CollectionExecutives?$filter=CollectionID eq 19483
Authorization: Basic {{username}} {{password}}

###
GET {{bromcom_odata_url}}/CollectionExecutives?$orderby=StaffID
Authorization: Basic {{username}} {{password}}


###
GET https://cloudmis.bromcom.com/Nucleus/OData/Collections?$filter=CollectionID%20eq%2019502
Authorization: Basic {{username}} {{password}}

###
GET https://cloudmis.bromcom.com/Nucleus/OData/Students?$filter=(StudentId eq 1052 or StudentId eq 2012 or StudentId eq 1934)
Authorization: Basic {{username}} {{password}}

###
GET https://cloudmis.bromcom.com/Nucleus/OData/BehaviourEventRecords
Authorization: Basic {{username}} {{password}}

###
GET https://cloudmis.bromcom.com/Nucleus/OData/Students
Authorization: Basic {{username}} {{password}}

###
GET https://cloudmis.bromcom.com/Nucleus/OData/StudentClasses
Authorization: Basic {{username}} {{password}}

###
GET https://cloudmis.bromcom.com/Nucleus/OData/StudentClasses?$filter=ClassName%20eq%20%2712B/Cm%27
Authorization: Basic {{username}} {{password}}

###
GET https://cloudmis.bromcom.com/Nucleus/OData/StudentClasses?$filter=ClassId eq 19502
Authorization: Basic {{username}} {{password}}